config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'projects#index'
  resources :projects, only: [:create, :destroy, :index] do
    resources :todos, only: [:index, :create, :destroy, :update, :edit]
  end

  resources :tags, only: [:index, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true

  has_many :todos, dependent: :destroy

end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true

  has_many :todo_tag_relationships, class_name: 'TodoTagRelationship',
                                    foreign_key: 'tag_id',
                                    dependent: :destroy

  has_many :todos, through: :todo_tag_relationships, source: :todo
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :project
  has_many :todo_tag_relationships, class_name: 'TodoTagRelationship',
                                    foreign_key: 'todo_id',
                                    dependent: :destroy

  has_many :tags, through: :todo_tag_relationships, source: :tag

  validates :content, presence: true, allow_nil: true
  validates_inclusion_of :completed, in: [true, false], allow_nil: true
  validates :deadline, presence: true, allow_nil: true

  def self.todos_filter(todos, filter)
    begin
      if filter.keys.size == 2 && (filter['date_to'][0].blank? && filter['date_to'][0].blank?)
        return all
      end
    rescue StandardError
      return all
    end

    filter_tags = []
    filter_completed = []

    filter.each do |param|
      filter_field_key = param[0]
      filter_field_value = param[1]
      if filter_field_key.eql?('tags')
        filter_field_value.each do |tag_pair|
          tag_id = tag_pair[0]
          filter_tags << tag_id if tag_pair[1].eql?('on')
        end
      elsif filter_field_key.eql?('completed')
        filter_field_value.each do |completed_pair|
          filter_completed << true if completed_pair[0].eql?('done') && completed_pair[1].eql?('on')
          filter_completed << false if completed_pair[0].eql?('todo') && completed_pair[1].eql?('on')
        end
      end
    end

    todos = todos.where('completed IN (?)', filter_completed) if filter_completed.size.positive?
    todos = todos.where('deadline >= (?)', filter['date_from']) unless filter['date_from'][0].blank?
    todos = todos.where('deadline <= (?)', filter['date_to']) unless filter['date_to'][0].blank?
    tags = TodoTagRelationship.where('tag_id in (?)', filter_tags).select('todo_id')
    todos = todos.where('id in (?)', tags)
    return todos
  end
end

app/models/todo_tag_relationship.rb
class TodoTagRelationship < ApplicationRecord
  belongs_to :todo, class_name: 'Todo'
  belongs_to :tag, class_name: 'Tag'

  validates :todo_id, presence: true
  validates :tag_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include TodosHelper
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all.paginate(page: params[:page])
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @projects = []
    if @project.save
      redirect_to root_path
    else
      render 'index'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to root_path
  end

  private
  def project_params
    params
        .require(:project)
        .permit(:name)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tag = Tag.new
    @tags = Tag.all.paginate(page: params[:page])
  end

  def create
    @tag = Tag.new(tag_params)
    @tags = []
    if @tag.save
      redirect_to tags_path
    else
      render 'tags/index'
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to tags_path
  end

  private
  def tag_params
    params
        .require(:tag)
        .permit(:name)
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  before_action :get_project, only: [:index, :edit, :update, :destroy, :create]

  def index
    @all_tags = Tag.all
    @todo_tags = []

    @all_todos = @project.todos.includes(:tags)
    @todos = @all_todos.todos_filter(@all_todos, params['filter']).paginate(page: params[:page], per_page: 20)
    @todo = Todo.new
  end

  def edit
    @all_tags = Tag.all

    @todo = @project.todos.find(params[:id])
    tag_ids = @todo.tags.ids
    @todo_tags = tag_ids.nil? ? [] : tag_ids
  end

  def create
    @todo = @project.todos.new(todo_params)
    @todos = []
    if @todo.save
      redirect_to project_todos_path
    else
      render 'todos/index'
    end

    @todo.tags = get_tags_from_params # posso mover isto lá para cima e fazer apenas 1 save?
    @todo.save
  end

  def update
    @todo = @project.todos.find(params[:id])
    @todos = []
    tag_ids = @todo.tags.ids
    @todo_tags = tag_ids.nil? ? [] : tag_ids

    p = todo_params
    c = nil
    c = p[:completed] unless p[:completed].nil?
    if @todo.update_attributes(
      content: (
        if p[:content].nil?
          @todo.content
        else
          p[:content]
        end
      ),
      completed: (if !c.nil?
                    c
                  else
                    @todo.completed
                  end),
      deadline: (
        if p[:deadline].nil?
          @todo.deadline
        else
          p[:deadline]
        end
      )
    )
      redirectTo(project_todos_path)
    else
      render 'todos/edit'
    end

    # caso em que se faz update ao status do to do e nao se enviam as tags (nao queremos apagar as tags que lá estavam)
    @todo.tags = get_tags_from_params unless c && params[:tags].nil?
    @todo.save # refatorizar para fazer apenas 1 save?
  end

  def destroy
    @todo = @project.todos.find(params[:id])
    @todo.destroy
    redirect_to project_todos_path
  end

  private

  def redirectTo(path)
    respond_to do |format|
      format.html { redirect_to path }
      format.js
    end
  end

  def get_tags_from_params
    tags = []
    params[:tags]&.each do |t|
      t_id = Integer(t[0]) rescue nil
      tags << Tag.find(t_id) if t_id && t[1] == '1'
    end
    
    return tags
  end

  def get_project
    @project = Project.find(params[:project_id])
  end

  def todo_params
    params
      .require(:todo)
      .permit(:content, :completed, :deadline)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "Todos", root_path , id: "logo" %>
    </div>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Projects", root_path %></li>
        <li><%= link_to "Tags", tags_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default_head.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | TodoApp</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js" type="text/javascript"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" type="text/javascript"></script>
    <%= render 'layouts/rails_default_head' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container-fluid">
      <div class="center text_center">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/projects/_project.html.erb
<div class = "project_container">
  <div class = "project">
    <div class="project_item">
      <%= link_to project.name, project_todos_path(project.id) %>
    </div>

    <div class="project_options">
      <%= link_to(project, method: :delete) do %>
        <i class="fa fa-trash"></i>
      <% end %>
    </div>
  </div>

  <hr>
</div>

app/views/projects/_project_form.html.erb
<div class = "project_form">
  <%= form_with(model: @project, local:true) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <div class="field">
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/index.html.erb
<% provide(:title, "Home") %>
<% provide(:button_text, "Create Project") %>
<%= render 'project_form' %>

<hr>

<% if @projects.any?%>
  <div class = "projects">
    <%= render @projects %>
  </div>
  <%= will_paginate @projects %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/tags/_tag.html.erb
<div class = "tag">
  <span class = "tag_item">
    <%= tag.name %>
  </span>

  <div class="tag_item">
    <%= link_to(tag_path(tag.id), method: :delete) do %>
      <i class="fa fa-trash"></i>
    <% end %>
  </div>
</div>

app/views/tags/_tag_form.html.erb
<div class = "project_form">
  <%= form_with(model: @tag, local:true) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <div class="field">
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/tags/create.html.erb
<h1>Tags#create</h1>
<p>Find me in app/views/tags/create.html.erb</p>

app/views/tags/delete.html.erb
<h1>Tags#delete</h1>
<p>Find me in app/views/tags/delete.html.erb</p>

app/views/tags/index.html.erb
<% provide(:title, "Tags") %>
<% provide(:button_text, "Create Tag") %>
<%= render 'tag_form' %>

<hr>
<% if @tags.any?%>
  <div class = "tags">
    <%= render @tags %>
  </div>
  <%= will_paginate @tags %>
<% end %>

app/views/todos/_filter_form.html.erb
<aside class = "filter_form">
  <%= form_tag project_todos_path(@project.id), method: :get do %>
    <div class = "filter_form_group">
      <label>Filter by TAG:</label>
        <% @all_tags.each do |tag| %>
          <div class = "filter_form_field">
            <label> <%= tag.name %> </label>
            <%= check_box_tag "filter[tags][#{tag.id}]", params["filter[tags][#{tag.id}]"] %>
          </div>
        <% end %>
    </div>

    <div class = "filter_form_group">
      <label>Filter by Status:</label>

      <div class = "filter_form_field">
        <label>To Do</label>
        <%= check_box_tag "filter[completed][todo]", params["filter[completed][todo]"] %>
      </div>

      <div class = "filter_form_field">
        <label>Done</label>
        <%= check_box_tag "filter[completed][done]", params["filter[completed][done]"] %>
      </div>
    </div>

    <div class = "filter_form_group">
      <label>Filter by Date:</label>
      <div class = "filter_form_field">
        <label>From</label>
        <%= date_field "filter[date_from]", params["filter[date_from]"] %>
      </div>
      <div class = "filter_form_field">
        <label>To</label>
        <%= date_field "filter[date_to]", params["filter[date_to]"] %>
      </div>
    </div>

    <%= submit_tag "Filter" %>
    <div>
      <%= link_to "Clear Filters", project_todos_path(@project.id) %>
    </div>

  <% end %>
</aside>

app/views/todos/_todo.html.erb
<div class="todo_container">
  <div class = "todo" id="div_todo_id_<%= todo.id %>">
    <div class = "todo_field">
      <!--  Checkbox Field that patches the database-->
      <%= form_for todo, url: project_todo_path(@project.id, todo.id), data: { remote: true }, html: {id: "todo_checkbox"} do |f| %>
        <%= f.check_box :completed, :onclick => "$('#submit_checkbox_#{todo.id}').click()"%>
        <%= f.submit "Update", id: "#{"submit_checkbox_#{todo.id}"}", style:"#{'display: none'}" %>
      <% end %>
    </div>

    <span class = "todo_field">
      <% if todo.tags.any? %>
        <% todo.tags.each do |tag| %>
          <div class = "todo_tag_container">
            <span class = "todo_tag_text">
              <%= "#{tag.name}" %>
            </span>
          </div>
        <% end %>
      <% end %>
    </span>

    <span id="todo_field_content" class = "todo_field">
      <%= todo.content %>
    </span>

    <% if todo.deadline %>
      <span id="todo_field_deadline" class = "todo_field">
        <%= todo.deadline %>
      </span>
    <% end %>

    <div class="todo_options">
      <div class="todo_option">
        <%= link_to(edit_project_todo_path(@project.id, todo.id)) do %>
          <i class="fa fa-edit"></i>
        <% end %>
      </div>

      <div class="todo_option">
        <%= link_to(project_todo_path(@project.id, todo.id), method: :delete,
                    data: { remote: true }) do %>
          <i class="fa fa-trash"></i>
        <% end %>
      </div>
    </div>
  </div>

  <hr>

</div>

app/views/todos/_todo_form.html.erb
<div class = "todo_form">
  <%= form_with(model: [@project, @todo], local:true) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <div class="todo_form_field">
      <button type="button" class="tags_collapsible">
        <%= f.label :tags %>
        <i id="tags_collapsible_button_icon" class="fa fa-caret-down"></i>
      </button>
      <div class="tags_collapse_content">
        <% @all_tags.each do |t| %>
          <div>
            <%= label_tag t.name %>
            <%= check_box_tag "tags[#{t.id}]", value = "1", checked = @todo_tags.include?(t.id) ? true : false %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="todo_form_field">
      <%= f.label :content %>
      <%= f.text_field :content, placeholder: "Your new todos...", autocomplete: "off" %>
      <div id = "todo_content_suggestions">
      </div>
    </div>

    <div class="todo_form_field">
      <%= f.label :deadline %>
      <%= f.date_field :deadline %>
    </div>

    <div class="todo_form_field">
      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    </div>
  <% end %>


  <script>
    //$(document).on('turbolinks:load', function() {
      /* collapsable tags code */
      var collapse_div = document.getElementsByClassName("tags_collapsible");
      var button = document.getElementById("tags_collapsible_button_icon");
      var i;
      for (i = 0; i < collapse_div.length; i++) {
          collapse_div[i].addEventListener("click", function() {
              debugger
              var content = this.nextElementSibling;
              if (content.style.display === "block") {
                  content.style.display = "none";
                  button.className = "fa fa-caret-down"
              } else {
                  content.style.display = "block";
                  button.className = "fa fa-caret-up"
              }
          });
      }
    //})

    $('#todo_content').on("change paste keyup", function(e) {
        var todo_pair = <% if @all_todos.nil? %>
        <%= [] %>
        <% else %>
        <%= raw @all_todos.map { |todo| [todo.id, todo.content] } %>
        <% end %>

        let suggestions_field = document.getElementById("todo_content_suggestions");
        if (todo_pair.length > 0 && e.target.value.length > 0) {
            let suggestions = todo_pair.filter(n => n[1].startsWith(e.target.value));
            if (suggestions.length > 0) {
                suggestions_field.innerHTML = "";
                suggestions.forEach(function (item, index) {
                    var buttonTag = document.createElement("button");
                    buttonTag.class = "todo_sugg_button";
                    buttonTag.type = "button";
                    buttonTag.onclick = function() {scrollIntoTodo(this, item[0]);};
                    buttonTag.innerHTML = item[1];
                    suggestions_field.appendChild(buttonTag);
                });
            } else {
                suggestions_field.innerHTML = "";
            }
        } else {
            suggestions_field.innerHTML = "";
        }
    });

    function scrollIntoTodo(e, todo_id) {
        var element = document.querySelector("#div_todo_id_"+todo_id);
        // smooth scroll to element and align it at the bottom
        element.scrollIntoView({ behavior: 'smooth', block: 'end'});
    }
  </script>
</div>

app/views/todos/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:button_text, "Update Todo") %>
<%= link_to '< Back', project_todos_path(@project.id) %>
<%= render 'todo_form' %>

app/views/todos/index.html.erb
<% provide(:title, "Todos") %>
<% provide(:button_text, "Add Todo") %>

<%= render 'todo_form' %>

<hr>

<div class = "flex_row">

  <div class="side">
    <%= render 'filter_form' %>
  </div>

  <div class="main">
    <% if @todos.any?%>
      <div class = "todos">
        <%= render @todos %>
      </div>
    <%= will_paginate @todos %>
    <% end %>
  </div>
</div>